---
- name: Configurar servidor de banco de dados
  hosts: db01

  user: vagrant
  become: yes
  vars_files:
    - vars/main.yaml
  
  vars:
    - dbname: "db01"
    - dbusername: "root"
    - dbpassword: "devopsmaonamassa"
  
  roles:
    - configuracao_default_so
    - role: geerlingguy.mysql # ansible-galaxy install geerlingguy.mysql